### ISSUE TITLE
论文对比实验

### ISSUE THREAD

**Issue by coderjifd** [Linfeng-Tang/SuperFusion#23]
请问大佬如何处理与UMF-CMGR的定量、定性对比，它这个方法好像只能处理固定大小像256*256的图像，是把它的结果resize回原来的大小计算指标吗

**Comment by Linfeng-Tang** [comment]
他好像可以处理不同尺寸的图像的吧 如果只能处理固定尺寸，可以源图像Resize到他要求的尺寸上计算。
